# Generated by Django 5.2.9 on 2026-06-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='country_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='federation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_obtain_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('RENEWING', 'En renouvellement')], max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='professional_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='professional_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='agents/photos/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='social_media',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
