# Generated by Django 5.2.9 on 2026-06-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentprofile_contact_email_agentprofile_country_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agency_role',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Disponible pour de nouveaux mandats'), ('LIMITED', 'Disponibilité limitée'), ('UNAVAILABLE', 'Non disponible actuellement')], max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='covered_markets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='intervention_countries',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='represents_mainly',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AgentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='agents/files/')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='agents.agentprofile')),
            ],
        ),
    ]
