---
deployment:
  tasks:
    - export DEPLOYPATH=/home/baitmtz/foot3
    - export PYTHONPATH=/home/baitmtz/virtualenv/foot3/3.12/bin
    - $PYTHONPATH/pip install -r $DEPLOYPATH/requirements.txt --quiet
    - $PYTHONPATH/python $DEPLOYPATH/manage.py migrate --noinput
    - $PYTHONPATH/python $DEPLOYPATH/manage.py collectstatic --noinput
    - mkdir -p $DEPLOYPATH/tmp && touch $DEPLOYPATH/tmp/restart.txt
