# Generated by Django 6.0 on 2025-12-12 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('diplomas_certificates', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('AMATEUR', 'Amateur'), ('PRO', 'Pro')], max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_club_name', models.CharField(blank=True, max_length=140)),
                ('current_club_country', models.CharField(blank=True, max_length=80)),
                ('current_club_division', models.CharField(blank=True, max_length=80)),
                ('current_club_start', models.DateField(blank=True, null=True)),
                ('current_club_end', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True)),
                ('has_agent_contract', models.BooleanField(default=False)),
                ('agent_full_name', models.CharField(blank=True, max_length=140)),
                ('agent_id', models.CharField(blank=True, max_length=50)),
                ('represent_self', models.BooleanField(default=True)),
                ('search_objective', models.CharField(blank=True, max_length=120)),
                ('target_club_notes', models.TextField(blank=True)),
                ('visibility_mode', models.CharField(choices=[('ALL', 'Pour tout le monde'), ('ALL_EXCEPT', 'Pour tout le monde sauf'), ('SOME', 'Pour quelques clubs')], default='ALL', max_length=15)),
                ('visibility_filters', models.JSONField(blank=True, default=dict)),
                ('visibility_exceptions', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.nationality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachPreviousClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=140)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('division', models.CharField(blank=True, max_length=80)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_clubs', to='coaches.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoachFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CV', 'CV (PDF)'), ('PHOTO', 'Photo'), ('VIDEO', 'Vidéo'), ('OTHER', 'Autre')], max_length=10)),
                ('file', models.FileField(upload_to='coaches/files/')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='coaches.coachprofile')),
            ],
        ),
    ]
