# Generated by Django 5.2.9 on 2026-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='has_transfermarkt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='transfermarkt_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
