# Generated by Django 5.2.9 on 2026-06-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_remove_coachprofile_represent_self_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='represent_self',
            field=models.BooleanField(default=False),
        ),
    ]
