# Generated by Django 6.0.3 on 2026-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('AMATEUR', 'Amateur'), ('PRO', 'Pro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='visibility_mode',
            field=models.CharField(choices=[('ALL', 'Pour tout le monde'), ('ALL_EXCEPT', 'Pour tout le monde sauf'), ('SOME', 'Pour quelques clubs')], default='ALL', max_length=15),
        ),
    ]
