# Generated by Django 5.2.9 on 2026-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_alter_coachprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('IN_CLUB', 'En poste'), ('FREE', 'Libre')], max_length=15),
        ),
    ]
