# Generated by Django 5.2.9 on 2026-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0007_coachprofile_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='currency',
            field=models.CharField(blank=True, default='EUR', max_length=10, null=True),
        ),
    ]
