# Generated by Django 5.2.9 on 2026-08-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0008_coachprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='agent_contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='agent_contract_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
