# Generated by Django 6.0.3 on 2026-08-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0009_coachprofile_agent_contract_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='represent_self',
        ),
        migrations.CreateModel(
            name='CoachStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=20)),
                ('matches', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.PositiveIntegerField(default=0)),
                ('tackles', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('key_passes', models.PositiveIntegerField(default=0)),
                ('dribbles', models.PositiveIntegerField(default=0)),
                ('shots', models.PositiveIntegerField(default=0)),
                ('competitions', models.JSONField(blank=True, default=list)),
                ('competitions_other', models.TextField(blank=True)),
                ('collective_results', models.JSONField(blank=True, default=list)),
                ('collective_results_other', models.TextField(blank=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='coaches.coachpreviousclub')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='coaches.coachprofile')),
            ],
        ),
    ]
