# Generated by Django 6.0.3 on 2026-08-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0010_remove_coachprofile_represent_self_coachstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachstat',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='clean_sheets',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='dribbles',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='goals_conceded',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='interceptions',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='key_passes',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='shots',
        ),
        migrations.RemoveField(
            model_name='coachstat',
            name='tackles',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/avatars/'),
        ),
        migrations.AlterField(
            model_name='coachfile',
            name='file_type',
            field=models.CharField(choices=[('CV', 'CV (PDF)'), ('PHOTO', 'Photo'), ('PROFILE_PHOTO', 'Photo de profil'), ('VIDEO', 'Vidéo'), ('OTHER', 'Autre')], max_length=20),
        ),
    ]
