# Generated by Django 6.0.3 on 2026-08-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0011_remove_coachstat_assists_and_more'),
        ('players', '0018_playerstat_collective_results_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='consent_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_parent_profiles', to='players.nationality'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], max_length=15),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_relation_other',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parents_declaration',
            field=models.FileField(blank=True, null=True, upload_to='coaches/parents/'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parents_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='profile_status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('PENDING_CONSENT', 'En cours de validation')], default='ACTIVE', max_length=20),
        ),
    ]
