# Generated by Django 5.2.10 on 2026-03-01 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=140, verbose_name='Nom du club')),
                ('function', models.CharField(blank=True, help_text='Ex: Président, Directeur sportif, Recruteur...', max_length=80, verbose_name='Fonction')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
