# Generated by Django 5.2.9 on 2026-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parent_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
