# Generated by Django 5.2.9 on 2026-06-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerprofile_parent_email_playerprofile_parent_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='salary_max',
            new_name='desired_salary',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='salary_min',
        ),
    ]
