# Generated by Django 5.2.9 on 2026-06-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_salary_max_playerprofile_desired_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('IN_CLUB', 'En poste'), ('FREE', 'Libre')], max_length=15),
        ),
    ]
