# Generated by Django 5.2.9 on 2026-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_playerprofile_has_transfermarkt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='represent_self',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='looking_for_agent',
            field=models.BooleanField(default=False),
        ),
    ]
