# Generated by Django 5.2.9 on 2026-06-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_remove_playerprofile_represent_self_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='represent_self',
            field=models.BooleanField(default=False),
        ),
    ]
