# Generated by Django 5.2.9 on 2026-06-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_playerprofile_represent_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpreviousclub',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='playerpreviousclub',
            name='start_date',
        ),
        migrations.AddField(
            model_name='playerpreviousclub',
            name='season',
            field=models.CharField(blank=True, help_text='Ex: 2023-2024', max_length=20),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.playerpreviousclub'),
        ),
    ]
