# Generated by Django 5.2.9 on 2026-06-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_playerstat_collective_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='consent_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='profile_status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('PENDING_CONSENT', 'En cours de validation')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerfile',
            name='file_type',
            field=models.CharField(choices=[('CV', 'CV (PDF)'), ('PHOTO', 'Photo'), ('PROFILE_PHOTO', 'Photo de profil'), ('VIDEO', 'Vidéo'), ('OTHER', 'Autre')], max_length=20),
        ),
    ]
