# Generated by Django 6.0.3 on 2026-07-17 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_playerprofile_consent_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='parent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parent_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parent_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to='players.nationality'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], max_length=15),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parent_relation_other',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
