# Generated by Django 6.0.3 on 2026-07-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='clean_sheets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='dribbles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='goals_conceded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='interceptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='key_passes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='shots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='tackles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='foot',
            field=models.CharField(blank=True, choices=[('R', 'Droit'), ('L', 'Gauche'), ('B', 'Les 2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('AMATEUR', 'Amateur'), ('PRO', 'Pro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='visibility_mode',
            field=models.CharField(choices=[('ALL', 'Pour tout le monde'), ('ALL_EXCEPT', 'Pour tout le monde sauf'), ('SOME', 'Pour quelques clubs')], default='ALL', max_length=15),
        ),
    ]
