# Generated by Django 6.0.3 on 2026-07-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_add_position_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='currency',
            field=models.CharField(blank=True, default='EUR', max_length=10, null=True),
        ),
    ]
