# Generated by Django 6.0.3 on 2026-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_playerprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/avatars/'),
        ),
    ]
