# Generated by Django 6.0.3 on 2026-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_playerprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='current_club_country',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('AMATEUR', 'Amateur'), ('PRO', 'Pro')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='visibility_mode',
            field=models.CharField(choices=[('ALL', 'Pour tout le monde'), ('ALL_EXCEPT', 'Pour tout le monde sauf'), ('SOME', 'Pour quelques clubs')], db_index=True, default='ALL', max_length=15),
        ),
    ]
