# Generated by Django 5.2.9 on 2026-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_alter_playerprofile_current_club_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='agent_contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='agent_contract_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
